name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        go: ["^1.15.0"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Go ${{ matrix.go }} in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Install tools
        env:
          GO111MODULE: on
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.31.0
          golangci-lint --version

      - name: Lint
        run: golangci-lint run ./... -v

      - name: Test
        run: ./go.test.sh
